set app.run host
songlin1026/taipei-day-trip-website pull request #2
Opened 2021-04-20 08:16 UTC by songlin1026

吳松霖
設定app.run(host="0.0.0.0",port=3000)

2021-04-20 08:24 UTC, cwpeng requested changes
分頁資料順序的部分，不要使用 ID 當依據，ID 也不一定每個數字都會有，另外也可能按照別的欄位排序也不一定，就如同我們之前做過的練習。

另外要在訊息中留下已上線的測試連結。

2021-04-21 05:48 UTC, songlin1026 commented
吳松霖
http://3.20.171.57:3000/api/attractions
http://3.20.171.57:3000/api/attractions?page=0&keyword=台北101
http://3.20.171.57:3000/api/attraction/121

2021-04-21 06:01 UTC, cwpeng requested changes
http://3.20.171.57:3000/api/attractions?page=0&keyword=台北
這是關鍵字搜尋，所以這個應該要有結果。

下一頁是：nextPage

2021-04-22 05:54 UTC, songlin1026 commented
吳松霖
http://3.20.171.57:3000/api/attractions
http://3.20.171.57:3000/api/attractions?page=0&keyword=藝術
http://3.20.171.57:3000/api/attraction/20

2021-04-22 06:31 UTC, cwpeng requested changes
大部份都 OK 了，但未篩選的最後一頁，nextPage 請設定成 null。

我指的是以下這一頁：
http://3.20.171.57:3000/api/attractions?page=25

2021-04-22 06:49 UTC, songlin1026 commented
吳松霖
http://3.20.171.57:3000/api/attractions?page=26
http://3.20.171.57:3000/api/attractions
http://3.20.171.57:3000/api/attractions?page=0&keyword=藝術
http://3.20.171.57:3000/api/attraction/26

2021-04-22 07:01 UTC, cwpeng approved these changes
Good Fix.

2021-04-22 07:02 UTC, merged